# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: component_state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import core_api_pb2 as core__api__pb2
import core_handover_pb2 as core__handover__pb2
import core_msg_header_pb2 as core__msg__header__pb2
import core_address_pb2 as core__address__pb2
import media_player_drv_state_pb2 as media__player__drv__state__pb2
import telephony_drv_state_pb2 as telephony__drv__state__pb2
import tco_api_pb2 as tco__api__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='component_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63omponent_state.proto\x1a\x0cnanopb.proto\x1a\x0e\x63ore_api.proto\x1a\x13\x63ore_handover.proto\x1a\x15\x63ore_msg_header.proto\x1a\x12\x63ore_address.proto\x1a\x1cmedia_player_drv_state.proto\x1a\x19telephony_drv_state.proto\x1a\rtco_api.proto\"S\n\tcor_state\x12=\n\x17\x63ore_peer_property_sync\x18\x01 \x01(\x0b\x32\x1a.core_peer_property_sync_tH\x00\x42\x07\n\x05state\"\xf3\x02\n\ttco_state\x12%\n\x0btest_state0\x18\x01 \x01(\x0b\x32\x0e.test_state0_tH\x00\x12%\n\x0btest_state1\x18\x02 \x01(\x0b\x32\x0e.test_state1_tH\x00\x12%\n\x0btest_state2\x18\x03 \x01(\x0b\x32\x0e.test_state2_tH\x00\x12%\n\x0btest_state3\x18\x04 \x01(\x0b\x32\x0e.test_state3_tH\x00\x12%\n\x0btest_state4\x18\x05 \x01(\x0b\x32\x0e.test_state4_tH\x00\x12%\n\x0btest_state5\x18\x06 \x01(\x0b\x32\x0e.test_state5_tH\x00\x12%\n\x0btest_state6\x18\x07 \x01(\x0b\x32\x0e.test_state6_tH\x00\x12%\n\x0btest_state7\x18\x08 \x01(\x0b\x32\x0e.test_state7_tH\x00\x12%\n\x0btest_state8\x18\t \x01(\x0b\x32\x0e.test_state8_tH\x00\x42\x07\n\x05state\"`\n\x18\x63ore_update_peer_state_t\x12\x1a\n\x03\x63or\x18\xf2\x1b \x01(\x0b\x32\n.cor_stateH\x00\x12\x1b\n\x03tco\x18\xd7\xa8\x01 \x01(\x0b\x32\n.tco_stateH\x00\x42\x0b\n\tpeer_compb\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,core__api__pb2.DESCRIPTOR,core__handover__pb2.DESCRIPTOR,core__msg__header__pb2.DESCRIPTOR,core__address__pb2.DESCRIPTOR,media__player__drv__state__pb2.DESCRIPTOR,telephony__drv__state__pb2.DESCRIPTOR,tco__api__pb2.DESCRIPTOR,])




_COR_STATE = _descriptor.Descriptor(
  name='cor_state',
  full_name='cor_state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='core_peer_property_sync', full_name='cor_state.core_peer_property_sync', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='state', full_name='cor_state.state',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=191,
  serialized_end=274,
)


_TCO_STATE = _descriptor.Descriptor(
  name='tco_state',
  full_name='tco_state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_state0', full_name='tco_state.test_state0', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_state1', full_name='tco_state.test_state1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_state2', full_name='tco_state.test_state2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_state3', full_name='tco_state.test_state3', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_state4', full_name='tco_state.test_state4', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_state5', full_name='tco_state.test_state5', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_state6', full_name='tco_state.test_state6', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_state7', full_name='tco_state.test_state7', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_state8', full_name='tco_state.test_state8', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='state', full_name='tco_state.state',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=277,
  serialized_end=648,
)


_CORE_UPDATE_PEER_STATE_T = _descriptor.Descriptor(
  name='core_update_peer_state_t',
  full_name='core_update_peer_state_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cor', full_name='core_update_peer_state_t.cor', index=0,
      number=3570, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tco', full_name='core_update_peer_state_t.tco', index=1,
      number=21591, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='peer_comp', full_name='core_update_peer_state_t.peer_comp',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=650,
  serialized_end=746,
)

_COR_STATE.fields_by_name['core_peer_property_sync'].message_type = core__api__pb2._CORE_PEER_PROPERTY_SYNC_T
_COR_STATE.oneofs_by_name['state'].fields.append(
  _COR_STATE.fields_by_name['core_peer_property_sync'])
_COR_STATE.fields_by_name['core_peer_property_sync'].containing_oneof = _COR_STATE.oneofs_by_name['state']
_TCO_STATE.fields_by_name['test_state0'].message_type = tco__api__pb2._TEST_STATE0_T
_TCO_STATE.fields_by_name['test_state1'].message_type = tco__api__pb2._TEST_STATE1_T
_TCO_STATE.fields_by_name['test_state2'].message_type = tco__api__pb2._TEST_STATE2_T
_TCO_STATE.fields_by_name['test_state3'].message_type = tco__api__pb2._TEST_STATE3_T
_TCO_STATE.fields_by_name['test_state4'].message_type = tco__api__pb2._TEST_STATE4_T
_TCO_STATE.fields_by_name['test_state5'].message_type = tco__api__pb2._TEST_STATE5_T
_TCO_STATE.fields_by_name['test_state6'].message_type = tco__api__pb2._TEST_STATE6_T
_TCO_STATE.fields_by_name['test_state7'].message_type = tco__api__pb2._TEST_STATE7_T
_TCO_STATE.fields_by_name['test_state8'].message_type = tco__api__pb2._TEST_STATE8_T
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state0'])
_TCO_STATE.fields_by_name['test_state0'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state1'])
_TCO_STATE.fields_by_name['test_state1'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state2'])
_TCO_STATE.fields_by_name['test_state2'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state3'])
_TCO_STATE.fields_by_name['test_state3'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state4'])
_TCO_STATE.fields_by_name['test_state4'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state5'])
_TCO_STATE.fields_by_name['test_state5'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state6'])
_TCO_STATE.fields_by_name['test_state6'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state7'])
_TCO_STATE.fields_by_name['test_state7'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_TCO_STATE.oneofs_by_name['state'].fields.append(
  _TCO_STATE.fields_by_name['test_state8'])
_TCO_STATE.fields_by_name['test_state8'].containing_oneof = _TCO_STATE.oneofs_by_name['state']
_CORE_UPDATE_PEER_STATE_T.fields_by_name['cor'].message_type = _COR_STATE
_CORE_UPDATE_PEER_STATE_T.fields_by_name['tco'].message_type = _TCO_STATE
_CORE_UPDATE_PEER_STATE_T.oneofs_by_name['peer_comp'].fields.append(
  _CORE_UPDATE_PEER_STATE_T.fields_by_name['cor'])
_CORE_UPDATE_PEER_STATE_T.fields_by_name['cor'].containing_oneof = _CORE_UPDATE_PEER_STATE_T.oneofs_by_name['peer_comp']
_CORE_UPDATE_PEER_STATE_T.oneofs_by_name['peer_comp'].fields.append(
  _CORE_UPDATE_PEER_STATE_T.fields_by_name['tco'])
_CORE_UPDATE_PEER_STATE_T.fields_by_name['tco'].containing_oneof = _CORE_UPDATE_PEER_STATE_T.oneofs_by_name['peer_comp']
DESCRIPTOR.message_types_by_name['cor_state'] = _COR_STATE
DESCRIPTOR.message_types_by_name['tco_state'] = _TCO_STATE
DESCRIPTOR.message_types_by_name['core_update_peer_state_t'] = _CORE_UPDATE_PEER_STATE_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cor_state = _reflection.GeneratedProtocolMessageType('cor_state', (_message.Message,), {
  'DESCRIPTOR' : _COR_STATE,
  '__module__' : 'component_state_pb2'
  # @@protoc_insertion_point(class_scope:cor_state)
  })
_sym_db.RegisterMessage(cor_state)

tco_state = _reflection.GeneratedProtocolMessageType('tco_state', (_message.Message,), {
  'DESCRIPTOR' : _TCO_STATE,
  '__module__' : 'component_state_pb2'
  # @@protoc_insertion_point(class_scope:tco_state)
  })
_sym_db.RegisterMessage(tco_state)

core_update_peer_state_t = _reflection.GeneratedProtocolMessageType('core_update_peer_state_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_UPDATE_PEER_STATE_T,
  '__module__' : 'component_state_pb2'
  # @@protoc_insertion_point(class_scope:core_update_peer_state_t)
  })
_sym_db.RegisterMessage(core_update_peer_state_t)


# @@protoc_insertion_point(module_scope)
