# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cor_shutdown_reason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cor_shutdown_reason.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63or_shutdown_reason.proto\x1a\x0cnanopb.proto\"k\n\x13\x63or_shutdown_reason\x12+\n\x0fshutdown_reason\x18\x01 \x01(\x0e\x32\x12.shutdown_reason_t\x12\'\n\rshutdown_type\x18\x02 \x01(\x0e\x32\x10.shutdown_type_t*\x88\x01\n\x11shutdown_reason_t\x12 \n\x1cSHUTDOWN_REASON_USER_REQUEST\x10\x00\x12\x1b\n\x17SHUTDOWN_REASON_BATTERY\x10\x01\x12\x18\n\x14SHUTDOWN_REASON_TEST\x10\x02\x12\x1a\n\x16SHUTDOWN_REASON_UPDATE\x10\x03*\x91\x01\n\x0fshutdown_type_t\x12\x16\n\x12SHUTDOWN_TYPE_NONE\x10\x00\x12\x17\n\x13SHUTDOWN_TYPE_SHELF\x10\x01\x12\x16\n\x12SHUTDOWN_TYPE_SHIP\x10\x02\x12\x17\n\x13SHUTDOWN_TYPE_RESET\x10\x03\x12\x1c\n\x18SHUTDOWN_TYPE_SWAP_RESET\x10\x04\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_SHUTDOWN_REASON_T = _descriptor.EnumDescriptor(
  name='shutdown_reason_t',
  full_name='shutdown_reason_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_REASON_USER_REQUEST', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_REASON_BATTERY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_REASON_TEST', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_REASON_UPDATE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=153,
  serialized_end=289,
)
_sym_db.RegisterEnumDescriptor(_SHUTDOWN_REASON_T)

shutdown_reason_t = enum_type_wrapper.EnumTypeWrapper(_SHUTDOWN_REASON_T)
_SHUTDOWN_TYPE_T = _descriptor.EnumDescriptor(
  name='shutdown_type_t',
  full_name='shutdown_type_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_TYPE_SHELF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_TYPE_SHIP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_TYPE_RESET', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTDOWN_TYPE_SWAP_RESET', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=292,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_SHUTDOWN_TYPE_T)

shutdown_type_t = enum_type_wrapper.EnumTypeWrapper(_SHUTDOWN_TYPE_T)
SHUTDOWN_REASON_USER_REQUEST = 0
SHUTDOWN_REASON_BATTERY = 1
SHUTDOWN_REASON_TEST = 2
SHUTDOWN_REASON_UPDATE = 3
SHUTDOWN_TYPE_NONE = 0
SHUTDOWN_TYPE_SHELF = 1
SHUTDOWN_TYPE_SHIP = 2
SHUTDOWN_TYPE_RESET = 3
SHUTDOWN_TYPE_SWAP_RESET = 4



_COR_SHUTDOWN_REASON = _descriptor.Descriptor(
  name='cor_shutdown_reason',
  full_name='cor_shutdown_reason',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shutdown_reason', full_name='cor_shutdown_reason.shutdown_reason', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shutdown_type', full_name='cor_shutdown_reason.shutdown_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=150,
)

_COR_SHUTDOWN_REASON.fields_by_name['shutdown_reason'].enum_type = _SHUTDOWN_REASON_T
_COR_SHUTDOWN_REASON.fields_by_name['shutdown_type'].enum_type = _SHUTDOWN_TYPE_T
DESCRIPTOR.message_types_by_name['cor_shutdown_reason'] = _COR_SHUTDOWN_REASON
DESCRIPTOR.enum_types_by_name['shutdown_reason_t'] = _SHUTDOWN_REASON_T
DESCRIPTOR.enum_types_by_name['shutdown_type_t'] = _SHUTDOWN_TYPE_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cor_shutdown_reason = _reflection.GeneratedProtocolMessageType('cor_shutdown_reason', (_message.Message,), {
  'DESCRIPTOR' : _COR_SHUTDOWN_REASON,
  '__module__' : 'cor_shutdown_reason_pb2'
  # @@protoc_insertion_point(class_scope:cor_shutdown_reason)
  })
_sym_db.RegisterMessage(cor_shutdown_reason)


# @@protoc_insertion_point(module_scope)
