# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cor_reboot_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cor_reboot_info.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63or_reboot_info.proto\x1a\x0cnanopb.proto\"O\n\x0f\x63or_reboot_info\x12\x1e\n\x0freboot_platform\x18\x01 \x01(\rB\x05\x92?\x02\x38\x08\x12\x1c\n\rreboot_reason\x18\x02 \x01(\rB\x05\x92?\x02\x38\x08\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_COR_REBOOT_INFO = _descriptor.Descriptor(
  name='cor_reboot_info',
  full_name='cor_reboot_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reboot_platform', full_name='cor_reboot_info.reboot_platform', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reboot_reason', full_name='cor_reboot_info.reboot_reason', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['cor_reboot_info'] = _COR_REBOOT_INFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cor_reboot_info = _reflection.GeneratedProtocolMessageType('cor_reboot_info', (_message.Message,), {
  'DESCRIPTOR' : _COR_REBOOT_INFO,
  '__module__' : 'cor_reboot_info_pb2'
  # @@protoc_insertion_point(class_scope:cor_reboot_info)
  })
_sym_db.RegisterMessage(cor_reboot_info)


_COR_REBOOT_INFO.fields_by_name['reboot_platform']._options = None
_COR_REBOOT_INFO.fields_by_name['reboot_reason']._options = None
# @@protoc_insertion_point(module_scope)
