# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cor_reboot_reason.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cor_reboot_reason.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63or_reboot_reason.proto\x1a\x0cnanopb.proto\"<\n\x11\x63or_reboot_reason\x12\'\n\rreboot_reason\x18\x01 \x01(\x0e\x32\x10.reboot_reason_t*\xc1\x05\n\x0freboot_reason_t\x12\x16\n\x12REBOOT_REASON_NONE\x10\x00\x12\x1a\n\x16REBOOT_REASON_POWER_ON\x10\x01\x12\x1a\n\x16REBOOT_REASON_FIRMWARE\x10\x02\x12\x1c\n\x18REBOOT_REASON_UART_BREAK\x10\x03\x12\x19\n\x15REBOOT_REASON_CHARGER\x10\x04\x12\"\n\x1eREBOOT_REASON_UNEXPECTED_RESET\x10\x05\x12\x17\n\x13REBOOT_REASON_PANIC\x10\x06\x12\x16\n\x12REBOOT_REASON_SDIO\x10\x07\x12$\n REBOOT_REASON_TOOLCMD_FULL_RESET\x10\x08\x12&\n\"REBOOT_REASON_TOOLCMD_SUBSYS_RESET\x10\t\x12\"\n\x1eREBOOT_REASON_APP_SUBSYS_RESET\x10\n\x12\x1b\n\x17REBOOT_REASON_APP_PANIC\x10\x0b\x12\x1e\n\x1aREBOOT_REASON_APP_WATCHDOG\x10\x0c\x12\x1a\n\x16REBOOT_REASON_WATCHDOG\x10\r\x12 \n\x1cREBOOT_REASON_DORMANT_WAKEUP\x10\x0e\x12\x1c\n\x18REBOOT_REASON_HOST_RESET\x10\x0f\x12\x1f\n\x1bREBOOT_REASON_TBRIDGE_RESET\x10\x10\x12\x1d\n\x19REBOOT_REASON_DEBUG_RESET\x10\x11\x12!\n\x1dREBOOT_REASON_REASON_RECEIVED\x10\x12\x12\x19\n\x15REBOOT_REASON_RST_PIN\x10\x13\x12!\n\x1dREBOOT_REASON_SUBSYSTEM_PANIC\x10\x14\x12$\n REBOOT_REASON_SUBSYSTEM_WATCHDOG\x10\x15\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_REBOOT_REASON_T = _descriptor.EnumDescriptor(
  name='reboot_reason_t',
  full_name='reboot_reason_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_POWER_ON', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_FIRMWARE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_UART_BREAK', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_CHARGER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_UNEXPECTED_RESET', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_PANIC', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_SDIO', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_TOOLCMD_FULL_RESET', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_TOOLCMD_SUBSYS_RESET', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_APP_SUBSYS_RESET', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_APP_PANIC', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_APP_WATCHDOG', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_WATCHDOG', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_DORMANT_WAKEUP', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_HOST_RESET', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_TBRIDGE_RESET', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_DEBUG_RESET', index=17, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_REASON_RECEIVED', index=18, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_RST_PIN', index=19, number=19,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_SUBSYSTEM_PANIC', index=20, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_REASON_SUBSYSTEM_WATCHDOG', index=21, number=21,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=104,
  serialized_end=809,
)
_sym_db.RegisterEnumDescriptor(_REBOOT_REASON_T)

reboot_reason_t = enum_type_wrapper.EnumTypeWrapper(_REBOOT_REASON_T)
REBOOT_REASON_NONE = 0
REBOOT_REASON_POWER_ON = 1
REBOOT_REASON_FIRMWARE = 2
REBOOT_REASON_UART_BREAK = 3
REBOOT_REASON_CHARGER = 4
REBOOT_REASON_UNEXPECTED_RESET = 5
REBOOT_REASON_PANIC = 6
REBOOT_REASON_SDIO = 7
REBOOT_REASON_TOOLCMD_FULL_RESET = 8
REBOOT_REASON_TOOLCMD_SUBSYS_RESET = 9
REBOOT_REASON_APP_SUBSYS_RESET = 10
REBOOT_REASON_APP_PANIC = 11
REBOOT_REASON_APP_WATCHDOG = 12
REBOOT_REASON_WATCHDOG = 13
REBOOT_REASON_DORMANT_WAKEUP = 14
REBOOT_REASON_HOST_RESET = 15
REBOOT_REASON_TBRIDGE_RESET = 16
REBOOT_REASON_DEBUG_RESET = 17
REBOOT_REASON_REASON_RECEIVED = 18
REBOOT_REASON_RST_PIN = 19
REBOOT_REASON_SUBSYSTEM_PANIC = 20
REBOOT_REASON_SUBSYSTEM_WATCHDOG = 21



_COR_REBOOT_REASON = _descriptor.Descriptor(
  name='cor_reboot_reason',
  full_name='cor_reboot_reason',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reboot_reason', full_name='cor_reboot_reason.reboot_reason', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=101,
)

_COR_REBOOT_REASON.fields_by_name['reboot_reason'].enum_type = _REBOOT_REASON_T
DESCRIPTOR.message_types_by_name['cor_reboot_reason'] = _COR_REBOOT_REASON
DESCRIPTOR.enum_types_by_name['reboot_reason_t'] = _REBOOT_REASON_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cor_reboot_reason = _reflection.GeneratedProtocolMessageType('cor_reboot_reason', (_message.Message,), {
  'DESCRIPTOR' : _COR_REBOOT_REASON,
  '__module__' : 'cor_reboot_reason_pb2'
  # @@protoc_insertion_point(class_scope:cor_reboot_reason)
  })
_sym_db.RegisterMessage(cor_reboot_reason)


# @@protoc_insertion_point(module_scope)
