# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core_address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core_address.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63ore_address.proto\x1a\x0cnanopb.proto\"O\n\x18\x63ore_48bit_address_api_t\x12\x12\n\x03nap\x18\x01 \x01(\rB\x05\x92?\x02\x38\x10\x12\x12\n\x03uap\x18\x02 \x01(\rB\x05\x92?\x02\x38\x08\x12\x0b\n\x03lap\x18\x03 \x01(\rb\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])




_CORE_48BIT_ADDRESS_API_T = _descriptor.Descriptor(
  name='core_48bit_address_api_t',
  full_name='core_48bit_address_api_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nap', full_name='core_48bit_address_api_t.nap', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uap', full_name='core_48bit_address_api_t.uap', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lap', full_name='core_48bit_address_api_t.lap', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['core_48bit_address_api_t'] = _CORE_48BIT_ADDRESS_API_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

core_48bit_address_api_t = _reflection.GeneratedProtocolMessageType('core_48bit_address_api_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_48BIT_ADDRESS_API_T,
  '__module__' : 'core_address_pb2'
  # @@protoc_insertion_point(class_scope:core_48bit_address_api_t)
  })
_sym_db.RegisterMessage(core_48bit_address_api_t)


_CORE_48BIT_ADDRESS_API_T.fields_by_name['nap']._options = None
_CORE_48BIT_ADDRESS_API_T.fields_by_name['uap']._options = None
# @@protoc_insertion_point(module_scope)
