# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core_msg_header.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core_msg_header.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63ore_msg_header.proto\x1a\x0cnanopb.proto\"\xc7\x01\n\x10\x63ore_msgHeader_t\x12\x1a\n\x0b\x64\x65stination\x18\x01 \x01(\rB\x05\x92?\x02\x38\x08\x12\x15\n\x06source\x18\x02 \x01(\rB\x05\x92?\x02\x38\x08\x12\x1d\n\x04type\x18\x03 \x01(\x0e\x32\x0f.core_msgType_t\x12\x11\n\x02id\x18\x04 \x01(\rB\x05\x92?\x02\x38\x08\x12%\n\x06\x65ntity\x18\x05 \x01(\x0e\x32\x15.core_msgEntityType_t\x12\x15\n\rtimesyncValid\x18\x06 \x01(\x08\x12\x10\n\x08timesync\x18\x07 \x01(\r\"\xe5\x01\n\x14\x63ore_msgHeaderWire_t\x12\x17\n\x08\x63omp_abv\x18\x01 \x01(\tB\x05\x92?\x02p\x03\x12\x19\n\nsource_abv\x18\x02 \x01(\tB\x05\x92?\x02p\x03\x12\x1d\n\x04type\x18\x03 \x01(\x0e\x32\x0f.core_msgType_t\x12\x11\n\x02id\x18\x04 \x01(\rB\x05\x92?\x02\x38\x08\x12\x17\n\x08trans_id\x18\x05 \x01(\rB\x05\x92?\x02\x38\x10\x12%\n\x06\x65ntity\x18\x07 \x01(\x0e\x32\x15.core_msgEntityType_t\x12\x15\n\rtimesyncValid\x18\x08 \x01(\x08\x12\x10\n\x08timesync\x18\t \x01(\r*\x86\x01\n\x0e\x63ore_msgType_t\x12\x14\n\x10\x43ORE_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43ORE_REQUEST\x10\x01\x12\x11\n\rCORE_RESPONSE\x10\x02\x12\x0e\n\nCORE_EVENT\x10\x03\x12\x10\n\x0c\x43ORE_COMMAND\x10\x04\x12\x17\n\x13\x43ORE_RESPONSE_ERROR\x10\x05*\xaa\x01\n\x14\x63ore_msgEntityType_t\x12\x1b\n\x17\x43ORE_ENTITY_UNSPECIFIED\x10\x00\x12\x14\n\x10\x43ORE_ENTITY_PEER\x10\x01\x12\x14\n\x10\x43ORE_ENTITY_CASE\x10\x02\x12\x18\n\x14\x43ORE_ENTITY_LEFT_BUD\x10\x04\x12\x19\n\x15\x43ORE_ENTITY_RIGHT_BUD\x10\x08\x12\x14\n\x10\x43ORE_ENTITY_TEST\x10\x10\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_CORE_MSGTYPE_T = _descriptor.EnumDescriptor(
  name='core_msgType_t',
  full_name='core_msgType_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CORE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_REQUEST', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_RESPONSE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_EVENT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_COMMAND', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_RESPONSE_ERROR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=474,
  serialized_end=608,
)
_sym_db.RegisterEnumDescriptor(_CORE_MSGTYPE_T)

core_msgType_t = enum_type_wrapper.EnumTypeWrapper(_CORE_MSGTYPE_T)
_CORE_MSGENTITYTYPE_T = _descriptor.EnumDescriptor(
  name='core_msgEntityType_t',
  full_name='core_msgEntityType_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CORE_ENTITY_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_ENTITY_PEER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_ENTITY_CASE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_ENTITY_LEFT_BUD', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_ENTITY_RIGHT_BUD', index=4, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORE_ENTITY_TEST', index=5, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=611,
  serialized_end=781,
)
_sym_db.RegisterEnumDescriptor(_CORE_MSGENTITYTYPE_T)

core_msgEntityType_t = enum_type_wrapper.EnumTypeWrapper(_CORE_MSGENTITYTYPE_T)
CORE_UNSPECIFIED = 0
CORE_REQUEST = 1
CORE_RESPONSE = 2
CORE_EVENT = 3
CORE_COMMAND = 4
CORE_RESPONSE_ERROR = 5
CORE_ENTITY_UNSPECIFIED = 0
CORE_ENTITY_PEER = 1
CORE_ENTITY_CASE = 2
CORE_ENTITY_LEFT_BUD = 4
CORE_ENTITY_RIGHT_BUD = 8
CORE_ENTITY_TEST = 16



_CORE_MSGHEADER_T = _descriptor.Descriptor(
  name='core_msgHeader_t',
  full_name='core_msgHeader_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='destination', full_name='core_msgHeader_t.destination', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='core_msgHeader_t.source', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='core_msgHeader_t.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='core_msgHeader_t.id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity', full_name='core_msgHeader_t.entity', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timesyncValid', full_name='core_msgHeader_t.timesyncValid', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timesync', full_name='core_msgHeader_t.timesync', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=239,
)


_CORE_MSGHEADERWIRE_T = _descriptor.Descriptor(
  name='core_msgHeaderWire_t',
  full_name='core_msgHeaderWire_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='comp_abv', full_name='core_msgHeaderWire_t.comp_abv', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002p\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_abv', full_name='core_msgHeaderWire_t.source_abv', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002p\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='core_msgHeaderWire_t.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='core_msgHeaderWire_t.id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trans_id', full_name='core_msgHeaderWire_t.trans_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity', full_name='core_msgHeaderWire_t.entity', index=5,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timesyncValid', full_name='core_msgHeaderWire_t.timesyncValid', index=6,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timesync', full_name='core_msgHeaderWire_t.timesync', index=7,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=471,
)

_CORE_MSGHEADER_T.fields_by_name['type'].enum_type = _CORE_MSGTYPE_T
_CORE_MSGHEADER_T.fields_by_name['entity'].enum_type = _CORE_MSGENTITYTYPE_T
_CORE_MSGHEADERWIRE_T.fields_by_name['type'].enum_type = _CORE_MSGTYPE_T
_CORE_MSGHEADERWIRE_T.fields_by_name['entity'].enum_type = _CORE_MSGENTITYTYPE_T
DESCRIPTOR.message_types_by_name['core_msgHeader_t'] = _CORE_MSGHEADER_T
DESCRIPTOR.message_types_by_name['core_msgHeaderWire_t'] = _CORE_MSGHEADERWIRE_T
DESCRIPTOR.enum_types_by_name['core_msgType_t'] = _CORE_MSGTYPE_T
DESCRIPTOR.enum_types_by_name['core_msgEntityType_t'] = _CORE_MSGENTITYTYPE_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

core_msgHeader_t = _reflection.GeneratedProtocolMessageType('core_msgHeader_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_MSGHEADER_T,
  '__module__' : 'core_msg_header_pb2'
  # @@protoc_insertion_point(class_scope:core_msgHeader_t)
  })
_sym_db.RegisterMessage(core_msgHeader_t)

core_msgHeaderWire_t = _reflection.GeneratedProtocolMessageType('core_msgHeaderWire_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_MSGHEADERWIRE_T,
  '__module__' : 'core_msg_header_pb2'
  # @@protoc_insertion_point(class_scope:core_msgHeaderWire_t)
  })
_sym_db.RegisterMessage(core_msgHeaderWire_t)


_CORE_MSGHEADER_T.fields_by_name['destination']._options = None
_CORE_MSGHEADER_T.fields_by_name['source']._options = None
_CORE_MSGHEADER_T.fields_by_name['id']._options = None
_CORE_MSGHEADERWIRE_T.fields_by_name['comp_abv']._options = None
_CORE_MSGHEADERWIRE_T.fields_by_name['source_abv']._options = None
_CORE_MSGHEADERWIRE_T.fields_by_name['id']._options = None
_CORE_MSGHEADERWIRE_T.fields_by_name['trans_id']._options = None
# @@protoc_insertion_point(module_scope)
