# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core_handover.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import core_address_pb2 as core__address__pb2
import core_api_pb2 as core__api__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='core_handover.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63ore_handover.proto\x1a\x0cnanopb.proto\x1a\x12\x63ore_address.proto\x1a\x0e\x63ore_api.proto\"P\n\x1d\x63ore_handoverDataHeaderWire_t\x12\x17\n\x08\x63omp_abv\x18\x01 \x01(\tB\x05\x92?\x02p\x03\x12\x16\n\x07stateId\x18\x02 \x01(\rB\x05\x92?\x02\x38\x08\"/\n\x19\x63ore_cm_security_status_t\x12\x12\n\nsecureLink\x18\x01 \x01(\x08\"r\n%core_cm_bluetooth_transport_details_t\x12\x34\n\tbtAddress\x18\x01 \x01(\x0b\x32\x19.core_48bit_address_api_tB\x06\x92?\x03\xb8\x01\x01\x12\x13\n\x0b\x63tkdEnabled\x18\x02 \x01(\x08\"\xcb\x01\n\x19\x63ore_cm_connection_data_t\x12\x12\n\x03mtu\x18\x01 \x01(\rB\x05\x92?\x02\x38\x10\x12\x34\n\x08security\x18\x02 \x01(\x0b\x32\x1a.core_cm_security_status_tB\x06\x92?\x03\xb8\x01\x01\x12\x1a\n\x12protocolPacketized\x18\x03 \x01(\x08\x12H\n\x10transportDetails\x18\x04 \x01(\x0b\x32&.core_cm_bluetooth_transport_details_tB\x06\x92?\x03\xb8\x01\x01\"\xe3\x01\n\x1d\x63ore_cm_transport_tbl_entry_t\x12\x1b\n\x0c\x63onnectionId\x18\x01 \x01(\rB\x05\x92?\x02\x38\x08\x12&\n\ttransport\x18\x02 \x01(\x0e\x32\x13.cor_cm_transport_t\x12$\n\x08protocol\x18\x03 \x01(\x0e\x32\x12.cor_cm_protocol_t\x12\x1b\n\x13writeBytesAvailable\x18\x04 \x01(\r\x12:\n\x0e\x63onnectionData\x18\x05 \x01(\x0b\x32\x1a.core_cm_connection_data_tB\x06\x92?\x03\xb8\x01\x01\"b\n\x17\x63ore_cm_handover_data_t\x12G\n\x0ctransportTbl\x18\x01 \x03(\x0b\x32\x1e.core_cm_transport_tbl_entry_tB\x11\x92?\x02\x10\x02\x92?\x03\x80\x01\x01\x92?\x03\xb8\x01\x01\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,core__address__pb2.DESCRIPTOR,core__api__pb2.DESCRIPTOR,])




_CORE_HANDOVERDATAHEADERWIRE_T = _descriptor.Descriptor(
  name='core_handoverDataHeaderWire_t',
  full_name='core_handoverDataHeaderWire_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='comp_abv', full_name='core_handoverDataHeaderWire_t.comp_abv', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002p\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stateId', full_name='core_handoverDataHeaderWire_t.stateId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=153,
)


_CORE_CM_SECURITY_STATUS_T = _descriptor.Descriptor(
  name='core_cm_security_status_t',
  full_name='core_cm_security_status_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='secureLink', full_name='core_cm_security_status_t.secureLink', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=202,
)


_CORE_CM_BLUETOOTH_TRANSPORT_DETAILS_T = _descriptor.Descriptor(
  name='core_cm_bluetooth_transport_details_t',
  full_name='core_cm_bluetooth_transport_details_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='btAddress', full_name='core_cm_bluetooth_transport_details_t.btAddress', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctkdEnabled', full_name='core_cm_bluetooth_transport_details_t.ctkdEnabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=318,
)


_CORE_CM_CONNECTION_DATA_T = _descriptor.Descriptor(
  name='core_cm_connection_data_t',
  full_name='core_cm_connection_data_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mtu', full_name='core_cm_connection_data_t.mtu', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='security', full_name='core_cm_connection_data_t.security', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocolPacketized', full_name='core_cm_connection_data_t.protocolPacketized', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transportDetails', full_name='core_cm_connection_data_t.transportDetails', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=524,
)


_CORE_CM_TRANSPORT_TBL_ENTRY_T = _descriptor.Descriptor(
  name='core_cm_transport_tbl_entry_t',
  full_name='core_cm_transport_tbl_entry_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connectionId', full_name='core_cm_transport_tbl_entry_t.connectionId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transport', full_name='core_cm_transport_tbl_entry_t.transport', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='core_cm_transport_tbl_entry_t.protocol', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='writeBytesAvailable', full_name='core_cm_transport_tbl_entry_t.writeBytesAvailable', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connectionData', full_name='core_cm_transport_tbl_entry_t.connectionData', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=754,
)


_CORE_CM_HANDOVER_DATA_T = _descriptor.Descriptor(
  name='core_cm_handover_data_t',
  full_name='core_cm_handover_data_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transportTbl', full_name='core_cm_handover_data_t.transportTbl', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\020\002\222?\003\200\001\001\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=756,
  serialized_end=854,
)

_CORE_CM_BLUETOOTH_TRANSPORT_DETAILS_T.fields_by_name['btAddress'].message_type = core__address__pb2._CORE_48BIT_ADDRESS_API_T
_CORE_CM_CONNECTION_DATA_T.fields_by_name['security'].message_type = _CORE_CM_SECURITY_STATUS_T
_CORE_CM_CONNECTION_DATA_T.fields_by_name['transportDetails'].message_type = _CORE_CM_BLUETOOTH_TRANSPORT_DETAILS_T
_CORE_CM_TRANSPORT_TBL_ENTRY_T.fields_by_name['transport'].enum_type = core__api__pb2._COR_CM_TRANSPORT_T
_CORE_CM_TRANSPORT_TBL_ENTRY_T.fields_by_name['protocol'].enum_type = core__api__pb2._COR_CM_PROTOCOL_T
_CORE_CM_TRANSPORT_TBL_ENTRY_T.fields_by_name['connectionData'].message_type = _CORE_CM_CONNECTION_DATA_T
_CORE_CM_HANDOVER_DATA_T.fields_by_name['transportTbl'].message_type = _CORE_CM_TRANSPORT_TBL_ENTRY_T
DESCRIPTOR.message_types_by_name['core_handoverDataHeaderWire_t'] = _CORE_HANDOVERDATAHEADERWIRE_T
DESCRIPTOR.message_types_by_name['core_cm_security_status_t'] = _CORE_CM_SECURITY_STATUS_T
DESCRIPTOR.message_types_by_name['core_cm_bluetooth_transport_details_t'] = _CORE_CM_BLUETOOTH_TRANSPORT_DETAILS_T
DESCRIPTOR.message_types_by_name['core_cm_connection_data_t'] = _CORE_CM_CONNECTION_DATA_T
DESCRIPTOR.message_types_by_name['core_cm_transport_tbl_entry_t'] = _CORE_CM_TRANSPORT_TBL_ENTRY_T
DESCRIPTOR.message_types_by_name['core_cm_handover_data_t'] = _CORE_CM_HANDOVER_DATA_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

core_handoverDataHeaderWire_t = _reflection.GeneratedProtocolMessageType('core_handoverDataHeaderWire_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_HANDOVERDATAHEADERWIRE_T,
  '__module__' : 'core_handover_pb2'
  # @@protoc_insertion_point(class_scope:core_handoverDataHeaderWire_t)
  })
_sym_db.RegisterMessage(core_handoverDataHeaderWire_t)

core_cm_security_status_t = _reflection.GeneratedProtocolMessageType('core_cm_security_status_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_CM_SECURITY_STATUS_T,
  '__module__' : 'core_handover_pb2'
  # @@protoc_insertion_point(class_scope:core_cm_security_status_t)
  })
_sym_db.RegisterMessage(core_cm_security_status_t)

core_cm_bluetooth_transport_details_t = _reflection.GeneratedProtocolMessageType('core_cm_bluetooth_transport_details_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_CM_BLUETOOTH_TRANSPORT_DETAILS_T,
  '__module__' : 'core_handover_pb2'
  # @@protoc_insertion_point(class_scope:core_cm_bluetooth_transport_details_t)
  })
_sym_db.RegisterMessage(core_cm_bluetooth_transport_details_t)

core_cm_connection_data_t = _reflection.GeneratedProtocolMessageType('core_cm_connection_data_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_CM_CONNECTION_DATA_T,
  '__module__' : 'core_handover_pb2'
  # @@protoc_insertion_point(class_scope:core_cm_connection_data_t)
  })
_sym_db.RegisterMessage(core_cm_connection_data_t)

core_cm_transport_tbl_entry_t = _reflection.GeneratedProtocolMessageType('core_cm_transport_tbl_entry_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_CM_TRANSPORT_TBL_ENTRY_T,
  '__module__' : 'core_handover_pb2'
  # @@protoc_insertion_point(class_scope:core_cm_transport_tbl_entry_t)
  })
_sym_db.RegisterMessage(core_cm_transport_tbl_entry_t)

core_cm_handover_data_t = _reflection.GeneratedProtocolMessageType('core_cm_handover_data_t', (_message.Message,), {
  'DESCRIPTOR' : _CORE_CM_HANDOVER_DATA_T,
  '__module__' : 'core_handover_pb2'
  # @@protoc_insertion_point(class_scope:core_cm_handover_data_t)
  })
_sym_db.RegisterMessage(core_cm_handover_data_t)


_CORE_HANDOVERDATAHEADERWIRE_T.fields_by_name['comp_abv']._options = None
_CORE_HANDOVERDATAHEADERWIRE_T.fields_by_name['stateId']._options = None
_CORE_CM_BLUETOOTH_TRANSPORT_DETAILS_T.fields_by_name['btAddress']._options = None
_CORE_CM_CONNECTION_DATA_T.fields_by_name['mtu']._options = None
_CORE_CM_CONNECTION_DATA_T.fields_by_name['security']._options = None
_CORE_CM_CONNECTION_DATA_T.fields_by_name['transportDetails']._options = None
_CORE_CM_TRANSPORT_TBL_ENTRY_T.fields_by_name['connectionId']._options = None
_CORE_CM_TRANSPORT_TBL_ENTRY_T.fields_by_name['connectionData']._options = None
_CORE_CM_HANDOVER_DATA_T.fields_by_name['transportTbl']._options = None
# @@protoc_insertion_point(module_scope)
