# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: media_player_drv_state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import core_address_pb2 as core__address__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='media_player_drv_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cmedia_player_drv_state.proto\x1a\x0cnanopb.proto\x1a\x12\x63ore_address.proto\"a\n\x12mplDrv_bt_device_t\x12/\n\x04\x61\x64\x64r\x18\x01 \x01(\x0b\x32\x19.core_48bit_address_api_tB\x06\x92?\x03\xb8\x01\x01\x12\x1a\n\x0bplaybackPos\x18\x02 \x01(\rB\x05\x92?\x02\x38\x10\"R\n\x17mplDrv_state_instance_t\x12\x37\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x13.mplDrv_bt_device_tB\x11\x92?\x02\x10\x02\x92?\x03\x80\x01\x01\x92?\x03\xb8\x01\x01\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,core__address__pb2.DESCRIPTOR,])




_MPLDRV_BT_DEVICE_T = _descriptor.Descriptor(
  name='mplDrv_bt_device_t',
  full_name='mplDrv_bt_device_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='mplDrv_bt_device_t.addr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playbackPos', full_name='mplDrv_bt_device_t.playbackPos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\020', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=163,
)


_MPLDRV_STATE_INSTANCE_T = _descriptor.Descriptor(
  name='mplDrv_state_instance_t',
  full_name='mplDrv_state_instance_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='mplDrv_state_instance_t.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\020\002\222?\003\200\001\001\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=247,
)

_MPLDRV_BT_DEVICE_T.fields_by_name['addr'].message_type = core__address__pb2._CORE_48BIT_ADDRESS_API_T
_MPLDRV_STATE_INSTANCE_T.fields_by_name['devices'].message_type = _MPLDRV_BT_DEVICE_T
DESCRIPTOR.message_types_by_name['mplDrv_bt_device_t'] = _MPLDRV_BT_DEVICE_T
DESCRIPTOR.message_types_by_name['mplDrv_state_instance_t'] = _MPLDRV_STATE_INSTANCE_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mplDrv_bt_device_t = _reflection.GeneratedProtocolMessageType('mplDrv_bt_device_t', (_message.Message,), {
  'DESCRIPTOR' : _MPLDRV_BT_DEVICE_T,
  '__module__' : 'media_player_drv_state_pb2'
  # @@protoc_insertion_point(class_scope:mplDrv_bt_device_t)
  })
_sym_db.RegisterMessage(mplDrv_bt_device_t)

mplDrv_state_instance_t = _reflection.GeneratedProtocolMessageType('mplDrv_state_instance_t', (_message.Message,), {
  'DESCRIPTOR' : _MPLDRV_STATE_INSTANCE_T,
  '__module__' : 'media_player_drv_state_pb2'
  # @@protoc_insertion_point(class_scope:mplDrv_state_instance_t)
  })
_sym_db.RegisterMessage(mplDrv_state_instance_t)


_MPLDRV_BT_DEVICE_T.fields_by_name['addr']._options = None
_MPLDRV_BT_DEVICE_T.fields_by_name['playbackPos']._options = None
_MPLDRV_STATE_INSTANCE_T.fields_by_name['devices']._options = None
# @@protoc_insertion_point(module_scope)
