# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telephony_drv_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import core_address_pb2 as core__address__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='telephony_drv_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19telephony_drv_state.proto\x1a\x0cnanopb.proto\x1a\x12\x63ore_address.proto\"W\n\x19telDrv_connection_state_t\x12\x1a\n\x12hfp_sco_connection\x18\x01 \x01(\x08\x12\x1e\n\x16hfp_profile_connection\x18\x02 \x01(\x08\"\xb2\x01\n\x12telDrv_bt_device_t\x12/\n\x04\x61\x64\x64r\x18\x01 \x01(\x0b\x32\x19.core_48bit_address_api_tB\x06\x92?\x03\xb8\x01\x01\x12<\n\x10\x63onnection_state\x18\x02 \x01(\x0b\x32\x1a.telDrv_connection_state_tB\x06\x92?\x03\xb8\x01\x01\x12-\n\tvoice_src\x18\x03 \x01(\x0e\x32\x13.telDrv_voice_src_tB\x05\x92?\x02\x38\x08\"R\n\x17telDrv_state_instance_t\x12\x37\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x13.telDrv_bt_device_tB\x11\x92?\x02\x10\x02\x92?\x03\x80\x01\x01\x92?\x03\xb8\x01\x01*\x94\x01\n\x12telDrv_voice_src_t\x12\x15\n\x11VOICE_SOURCE_NONE\x10\x00\x12\x16\n\x12VOICE_SOURCE_HFP_1\x10\x01\x12\x16\n\x12VOICE_SOURCE_HFP_2\x10\x02\x12\x14\n\x10VOICE_SOURCE_USB\x10\x03\x12!\n\x1dVOICE_SOURCE_LE_AUDIO_UNICAST\x10\x04\x62\x06proto3'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,core__address__pb2.DESCRIPTOR,])

_TELDRV_VOICE_SRC_T = _descriptor.EnumDescriptor(
  name='telDrv_voice_src_t',
  full_name='telDrv_voice_src_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOICE_SOURCE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VOICE_SOURCE_HFP_1', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VOICE_SOURCE_HFP_2', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VOICE_SOURCE_USB', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VOICE_SOURCE_LE_AUDIO_UNICAST', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=418,
  serialized_end=566,
)
_sym_db.RegisterEnumDescriptor(_TELDRV_VOICE_SRC_T)

telDrv_voice_src_t = enum_type_wrapper.EnumTypeWrapper(_TELDRV_VOICE_SRC_T)
VOICE_SOURCE_NONE = 0
VOICE_SOURCE_HFP_1 = 1
VOICE_SOURCE_HFP_2 = 2
VOICE_SOURCE_USB = 3
VOICE_SOURCE_LE_AUDIO_UNICAST = 4



_TELDRV_CONNECTION_STATE_T = _descriptor.Descriptor(
  name='telDrv_connection_state_t',
  full_name='telDrv_connection_state_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hfp_sco_connection', full_name='telDrv_connection_state_t.hfp_sco_connection', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hfp_profile_connection', full_name='telDrv_connection_state_t.hfp_profile_connection', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=150,
)


_TELDRV_BT_DEVICE_T = _descriptor.Descriptor(
  name='telDrv_bt_device_t',
  full_name='telDrv_bt_device_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='telDrv_bt_device_t.addr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connection_state', full_name='telDrv_bt_device_t.connection_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voice_src', full_name='telDrv_bt_device_t.voice_src', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=331,
)


_TELDRV_STATE_INSTANCE_T = _descriptor.Descriptor(
  name='telDrv_state_instance_t',
  full_name='telDrv_state_instance_t',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='telDrv_state_instance_t.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\020\002\222?\003\200\001\001\222?\003\270\001\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=415,
)

_TELDRV_BT_DEVICE_T.fields_by_name['addr'].message_type = core__address__pb2._CORE_48BIT_ADDRESS_API_T
_TELDRV_BT_DEVICE_T.fields_by_name['connection_state'].message_type = _TELDRV_CONNECTION_STATE_T
_TELDRV_BT_DEVICE_T.fields_by_name['voice_src'].enum_type = _TELDRV_VOICE_SRC_T
_TELDRV_STATE_INSTANCE_T.fields_by_name['devices'].message_type = _TELDRV_BT_DEVICE_T
DESCRIPTOR.message_types_by_name['telDrv_connection_state_t'] = _TELDRV_CONNECTION_STATE_T
DESCRIPTOR.message_types_by_name['telDrv_bt_device_t'] = _TELDRV_BT_DEVICE_T
DESCRIPTOR.message_types_by_name['telDrv_state_instance_t'] = _TELDRV_STATE_INSTANCE_T
DESCRIPTOR.enum_types_by_name['telDrv_voice_src_t'] = _TELDRV_VOICE_SRC_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

telDrv_connection_state_t = _reflection.GeneratedProtocolMessageType('telDrv_connection_state_t', (_message.Message,), {
  'DESCRIPTOR' : _TELDRV_CONNECTION_STATE_T,
  '__module__' : 'telephony_drv_state_pb2'
  # @@protoc_insertion_point(class_scope:telDrv_connection_state_t)
  })
_sym_db.RegisterMessage(telDrv_connection_state_t)

telDrv_bt_device_t = _reflection.GeneratedProtocolMessageType('telDrv_bt_device_t', (_message.Message,), {
  'DESCRIPTOR' : _TELDRV_BT_DEVICE_T,
  '__module__' : 'telephony_drv_state_pb2'
  # @@protoc_insertion_point(class_scope:telDrv_bt_device_t)
  })
_sym_db.RegisterMessage(telDrv_bt_device_t)

telDrv_state_instance_t = _reflection.GeneratedProtocolMessageType('telDrv_state_instance_t', (_message.Message,), {
  'DESCRIPTOR' : _TELDRV_STATE_INSTANCE_T,
  '__module__' : 'telephony_drv_state_pb2'
  # @@protoc_insertion_point(class_scope:telDrv_state_instance_t)
  })
_sym_db.RegisterMessage(telDrv_state_instance_t)


_TELDRV_BT_DEVICE_T.fields_by_name['addr']._options = None
_TELDRV_BT_DEVICE_T.fields_by_name['connection_state']._options = None
_TELDRV_BT_DEVICE_T.fields_by_name['voice_src']._options = None
_TELDRV_STATE_INSTANCE_T.fields_by_name['devices']._options = None
# @@protoc_insertion_point(module_scope)
